sudo: required
dist: trusty
language: python
cache:
  - pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
before_install:
  - sudo apt install rpm dpkg-dev debhelper dh-python python3-setuptools fakeroot python3-serial python3-yaml
install:
  - pip install pyusb
script:
  - python setup.py build
  - python setup.py test
