sudo: required
dist: trusty
language: python
cache:
  - pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
before_install:
  - sudo apt update
  - sudo apt install python3-setuptools python3-serial python3-yaml
install:
  - pip install pyusb
script:
  - python setup.py build
  - python setup.py test
